In [1]:
import numpy as np 
import pandas as pd
from collections import Counter
import lightgbm as lgb
import xgboost as xgb
import catboost as cbt
from pandas import DataFrame as DF
import gplearn
import tpot
import deap
from hyperopt import hp, fmin, rand, tpe, space_eval
from bayes_opt import BayesianOptimization
import time
import gc
from tqdm import tqdm
from sklearn.metrics import f1_score

/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [27]:
# train = pd.read_hdf("../cache_data/multiclass_6724.hdf","train")
# valid = pd.read_hdf("../cache_data/multiclass_6724.hdf","valid")
# test = pd.read_hdf("../cache_data/multiclass_6724.hdf","test")

# train.shape,valid.shape,test.shape

In [210]:
train = pd.read_hdf("../cache_data/lgb_model.hdf","train").sort_index()
test = pd.read_hdf("../cache_data/lgb_model.hdf","test").sort_index()

In [211]:
num_classes = 12
label_name = 'click_mode'
train.rename(columns={num_classes:label_name,'0':0,'1':1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9,'10':10,'11':11},inplace=True)
test.rename(columns={num_classes:label_name,'0':0,'1':1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9,'10':10,'11':11},inplace=True)

In [212]:
print(train['click_mode'].value_counts())
train['click_mode'].isnull().sum()

2.0     466176
0.0     324817
7.0     286659
1.0     274329
9.0     205343
5.0     187332
3.0      83194
10.0     51678
4.0      41587
6.0      40162
11.0     31830
8.0       6893
Name: click_mode, dtype: int64


0

In [217]:
raw_train_score = f1_score(train[label_name],np.argmax(train[range(num_classes)].values,axis=1),average='weighted')
#raw_valid_score = f1_score(valid[label_name],np.argmax(valid[range(num_classes)].values,axis=1),average='weighted')

raw_train_score,#raw_valid_score

(0.6844480445894455,)

In [218]:
class OptimizedRounder(object):
    def __init__(self):
        self.coef_ = 0
        self.coef_arr = []
        self.val_score = []

    def _kappa_loss(self, coef, X, y):
        X_p = DF(np.copy(X))
#         X_v = valid[range(num_classes)]
        for i in range(len(coef)):
            X_p[i] *= coef[i]
#             X_v[i] *= coef[i]
        
        l1 = f1_score(y, np.argmax(X_p.values,axis=1), average="weighted")
#         l2 = f1_score(valid[label_name], np.argmax(X_v.values,axis=1), average="weighted")
        
        self.coef_arr.append(coef)
#         self.val_score.append(l2)
        
        print(list(coef.astype(np.float16)),' Train score = ',l1.astype(np.float32))#,' Valid score =',l2.astype(np.float16))
        return -l1

    def fit(self, X, y):
        loss_partial = partial(self._kappa_loss, X=X, y=y) 
        self.coef_ = sp.optimize.minimize(loss_partial, initial_coef, method='Powell') 

    def predict(self, X, coef):
        X_p = DF(np.copy(X))
        for i in range(len(coef)):
            X_p[i] *= coef[i]
        return X_p

    def coefficients(self):
        return self.coef_['x']
    
#     def best_score(self):
#         return np.max(self.val_score)
    
#     def best_coef(self):
#         return self.coef_arr[np.argmax(self.val_score)]
# nelder-mead 
# Before =  0.6709307221687296
# After =  0.678495494646318
# GAP =  0.007564772477588355
# [0.92348139 0.71086394 0.65876489 1.55548237 1.73545927 0.62715862
#  1.45702358 0.59522381 1.18419033 0.57798275 0.90171286 1.05940425]

# Powell
# [1.36738918 1.03790291 0.77733245 2.33533351 3.25118434 0.82638933
#  1.9516095  0.95423545 1.52848168 0.88731548 1.19048762 1.12236339]

# Valid Counts =  Counter({2.0: 466176, 0.0: 324817, 7.0: 286659, 1.0: 274329, 9.0: 205343, 5.0: 187332, 3.0: 83194, 10.0: 51678, 4.0: 41587, 6.0: 40162, 11.0: 31830, 8.0: 6893})
# Predicted Counts =  Counter({2: 502354, 7: 312068, 1: 287486, 9: 265773, 0: 212699, 5: 200295, 10: 66450, 3: 46351, 11: 43035, 6: 31197, 4: 24955, 8: 7337})
# Before =  0.6709307221687296
# After =  0.6791416147396933
# GAP =  0.008210892570963635

In [219]:
cv_pred = train[range(num_classes)].values
y = train[label_name].values

In [208]:
# initial_coef = [1.1] * num_classes
# initial_coef = [1.26287028, 0.82937038, 0.5277721 , 1.64775053, 2.35868594,
#        0.60038381, 1.43501455, 0.74809782, 1.64015677, 0.75331299,
#        1.19730997, 0.91512994]
initial_coef = [1.19727551, 0.90333928, 0.68864398, 2.11965788, 2.66564214, 0.76702021,
                1.71968408, 0.81284811, 1.49193684, 0.784336,   1.0948337,  0.94776608] 

In [220]:
from functools import partial
import scipy as sp
from math import sqrt

optR = OptimizedRounder()
optR.fit(cv_pred, y)
best_score = optR.coefficients()
# (0.6770738132751616,)

[1.197, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6860828
[1.197, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6860828
[2.197, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68359727


/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[-0.4207, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.5884497
[1.197, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6860828
[0.579, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6858426
[1.579, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6857964
[1.059, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6860492
[1.343, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6860647
[1.223, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6860782
[1.145, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68609595
[1.111, 0.9033, 0.6885, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score = 

[1.186, 0.9404, 0.67, 2.111, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68613195
[1.186, 0.9404, 0.67, 2.14, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6861269
[1.186, 0.9404, 0.67, 2.123, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6861358
[1.186, 0.9404, 0.67, 2.121, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68613607
[1.186, 0.9404, 0.67, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68613607
[1.186, 0.9404, 0.67, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68613607
[1.186, 0.9404, 0.67, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68613607
[1.186, 0.9404, 0.67, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68613607
[1.186, 0.9404, 0.67, 2.12, 2.666, 0.767, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68613607


[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 0.1016, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.67871886
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.72, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68617934
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.102, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6861222
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 2.102, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68614405
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.661, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68616563
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.848, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6861799
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.945, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.68616354
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.785, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6861799
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.815, 0.813, 1.492, 0.784, 1.095, 0.9478]  Train score =  0.6861

[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.874, 0.784, 1.095, 0.9478]  Train score =  0.686169
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.567, 0.784, 1.095, 0.9478]  Train score =  0.6861833
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.337, 0.784, 1.095, 0.9478]  Train score =  0.68617827
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.784, 1.095, 0.9478]  Train score =  0.686185
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.49, 0.784, 1.095, 0.9478]  Train score =  0.686185
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.49, 0.784, 1.095, 0.9478]  Train score =  0.686185
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.49, 0.784, 1.095, 0.9478]  Train score =  0.686185
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.49, 0.784, 1.095, 0.9478]  Train score =  0.686185
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.784, 1.095, 0.9478]  Train score =  0.686185
[1.186, 0.9

[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.9478]  Train score =  0.686201
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.9478]  Train score =  0.686201
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.9478]  Train score =  0.686201
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.9478]  Train score =  0.686201
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.9478]  Train score =  0.686201
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.9478]  Train score =  0.686201
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.9478]  Train score =  0.686201
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.9478]  Train score =  0.686201
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 1.948]  Train score =  0.6861406
[

[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6862161
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6862161
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6862161
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6862161
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6862161
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6862161
[1.186, 0.9404, 1.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6860705
[1.186, 0.9404, -0.9478, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.45395926
[1.186, 0.9404, 0.67, 2.12, 3.594, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.68621

[1.186, 0.9404, 0.669, 2.121, 3.592, -0.9414, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.59956115
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.677, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6862169
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.0588, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.59956115
[1.186, 0.9404, 0.669, 2.121, 3.592, 1.059, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6861712
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.867, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6861714
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.4407, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.68573314
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.587, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.68612826
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.7495, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6861705
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.6426, 1.825, 0.813, 1.489, 0.9517, 1.095, 0.712]

[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, -0.1285, 0.9517, 1.095, 0.712]  Train score =  0.68467283
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 1.489, 0.9517, 1.095, 0.712]  Train score =  0.6862171
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 0.8716, 0.9517, 1.095, 0.712]  Train score =  0.6861331
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 1.871, 0.9517, 1.095, 0.712]  Train score =  0.6862034
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 1.576, 0.9517, 1.095, 0.712]  Train score =  0.68621397
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 1.254, 0.9517, 1.095, 0.712]  Train score =  0.68621093
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 1.438, 0.9517, 1.095, 0.712]  Train score =  0.6862193
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 1.368, 0.9517, 1.095, 0.712]  Train score =  0.6862132
[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 1.412, 0.9517, 1.095, 0

[1.186, 0.9404, 0.669, 2.121, 3.592, 0.676, 1.826, 0.8125, 1.438, 0.9487, 1.095, 0.769]  Train score =  0.68621683


In [221]:
best_coef = optR.coefficients()
best_coef#,best_score

array([1.18546017, 0.9404844 , 0.66918642, 2.12193384, 3.5909713 ,
       0.67592458, 1.82587149, 0.8126954 , 1.43834878, 0.94863208,
       1.09424807, 0.76961194])

In [223]:
print("Global Best")

pred_test_y_k = optR.predict(cv_pred, best_coef)
print(best_coef)
print("\nValid Counts = ", Counter(y))
print("Predicted Counts = ", Counter(np.argmax(pred_test_y_k.values,axis=1)))
acc1 = f1_score(y,np.argmax(cv_pred,axis=1),average="weighted")
acc2 = f1_score(y,np.argmax(pred_test_y_k.values,axis=1),average="weighted")
print("Train Before = ",acc1)
print("Train After = ",acc2)
print("Train GAP = ",acc2-acc1)

test_pred = optR.predict(test[range(num_classes)], best_coef)
test_pred = np.argmax(test_pred.values,axis=1)

Global Best
[1.18546017 0.9404844  0.66918642 2.12193384 3.5909713  0.67592458
 1.82587149 0.8126954  1.43834878 0.94863208 1.09424807 0.76961194]

Valid Counts =  Counter({2.0: 466176, 0.0: 324817, 7.0: 286659, 1.0: 274329, 9.0: 205343, 5.0: 187332, 3.0: 83194, 10.0: 51678, 4.0: 41587, 6.0: 40162, 11.0: 31830, 8.0: 6893})
Predicted Counts =  Counter({2: 500724, 7: 305544, 1: 281431, 9: 263300, 0: 225816, 5: 200693, 10: 67208, 3: 51317, 11: 39570, 6: 31095, 4: 24924, 8: 8378})
Train Before =  0.6844480445894455
Train After =  0.6862247141859121
Train GAP =  0.0017766695964666068


In [224]:
test_1 = pd.read_hdf("../cache_data/stack/677000_685361_post_powell.hdf","train")

In [225]:
for k in range(12):
    print(k,np.corrcoef(test_1[k],DF(pred_test_y_k)[k])[0][1])

0 0.82487611500043
1 0.9293025566523039
2 0.9757924986856176
3 0.7855396002527191
4 0.7485753840848436
5 0.9701076329672038
6 0.8313254092248018
7 0.9543064861065507
8 0.8454444546792
9 0.9619451043163072
10 0.9291262511372624
11 0.9462778960785544


In [226]:
np.corrcoef(np.argmax(test_1[range(num_classes)].values,axis=1),np.argmax(pred_test_y_k.values,axis=1))

array([[1.       , 0.9648866],
       [0.9648866, 1.       ]])

In [227]:
train_post = DF(pred_test_y_k).copy()
train_post.index = train.index
test_post = DF(optR.predict(test[range(num_classes)], best_coef)).copy()
test_post.index = test.index
train_post[12] = train['click_mode'].values
test_post[12] = np.nan

train_post.to_hdf("../cache_data/stack/{}_{}_post_powell.hdf".format(acc1,acc2),"train")
test_post.to_hdf("../cache_data/stack/{}_{}_post_powell.hdf".format(acc1,acc2),"test")

In [56]:
test['max_proba'] = test[range(num_classes)].values.max(axis=1)
test['max_proba_to_pred'] = test[range(num_classes)].values.argmax(axis=1)

In [229]:
test_pred = optR.predict(test[range(num_classes)], best_coef)
test_pred = np.argmax(test_pred.values,axis=1)

In [230]:
from collections import Counter
Counter(test_pred)

Counter({2: 89578,
         1: 46075,
         7: 55577,
         3: 6108,
         5: 33152,
         4: 3414,
         9: 29132,
         10: 8659,
         0: 24190,
         6: 2972,
         8: 1460,
         11: 4599})

In [148]:
test['label'] = (test['click_mode']==test['max_proba_to_pred']).astype(int)

In [231]:
find['label'].value_counts()

NameError: name 'find' is not defined

In [155]:
find[find['max_proba_to_pred']==2]#['label'].value_counts()

0         1         2         3         4         5         6  \
sid                                                                             
841034   0.018634  0.000835  0.944897  0.008138  0.004423  0.000186  0.002434   
841042   0.018853  0.000363  0.960628  0.013782  0.005126  0.000158  0.000058   
841043   0.017813  0.000321  0.971290  0.005021  0.004320  0.000136  0.000048   
841053   0.024359  0.000807  0.961608  0.005176  0.003302  0.000281  0.003301   
841134   0.016017  0.000339  0.969569  0.007396  0.005396  0.000145  0.000200   
841191   0.022472  0.000762  0.954330  0.013668  0.004284  0.000195  0.003059   
841201   0.014240  0.000286  0.974631  0.006016  0.003757  0.000120  0.000072   
841214   0.010201  0.000399  0.957273  0.003267  0.002797  0.000152  0.000055   
841215   0.009178  0.000298  0.982429  0.004196  0.002810  0.000122  0.000043   
841271   0.025012  0.000466  0.952510  0.015850  0.004548  0.000194  0.000069   
841315   0.028138  0.000491  0.932695  0.009096  0.007446  0.000205  0.000322   
841316   0.027776  0.000489  0.932046  0.008867  0.006885  0.000204  0.000333   
841332   0.018480  0.000398  0.967101  0.008240  0.004359  0.000164  0.000057   
841353   0.006912  0.000742  0.980705  0.005283  0.002532  0.001928  0.001146   
841389   0.024040  0.026209  0.904661  0.011890  0.013273  0.000294  0.000121   
841392   0.032885  0.034670  0.901465  0.019619  0.007035  0.000280  0.000098   
841445   0.005389  0.000536  0.985371  0.002523  0.002561  0.000129  0.001426   
841446   0.010012  0.017810  0.939318  0.004511  0.004745  0.000219  0.002745   
841483   0.021962  0.014814  0.951414  0.004199  0.004513  0.000210  0.000751   
841506   0.010228  0.000413  0.961929  0.006331  0.005139  0.000160  0.000586   
841524   0.006989  0.000382  0.983175  0.004689  0.003390  0.000159  0.000056   
841526   0.007124  0.000617  0.984138  0.003253  0.002397  0.000144  0.001218   
841533   0.010605  0.000997  0.976793  0.003922  0.002229  0.001899  0.002557   
841588   0.020898  0.025939  0.933980  0.009138  0.006819  0.000277  0.000114   
841602   0.006750  0.000251  0.987247  0.002405  0.002375  0.000102  0.000036   
841603   0.006811  0.000259  0.987159  0.002698  0.002111  0.000113  0.000039   
841604   0.007753  0.000327  0.974054  0.003393  0.002089  0.000136  0.000047   
841606   0.007550  0.000447  0.984622  0.003051  0.001815  0.000111  0.001630   
841608   0.014240  0.000809  0.952435  0.006556  0.002770  0.000166  0.000058   
841620   0.018435  0.031128  0.909536  0.010063  0.007779  0.000318  0.000132   
...           ...       ...       ...       ...       ...       ...       ...   
3395703  0.012715  0.001240  0.965583  0.005186  0.003902  0.007939  0.002184   
3395735  0.011341  0.000504  0.927834  0.002558  0.001605  0.000207  0.000082   
3395737  0.018115  0.025111  0.900588  0.004351  0.002623  0.000310  0.000118   
3395739  0.016320  0.030572  0.937901  0.006874  0.004511  0.000288  0.000115   
3395823  0.014721  0.001314  0.956271  0.008182  0.004866  0.000267  0.002358   
3395835  0.019733  0.000495  0.966387  0.007677  0.003812  0.000208  0.000075   
3395850  0.021824  0.000588  0.940620  0.011296  0.004406  0.000242  0.000578   
3395870  0.017739  0.000577  0.944943  0.008026  0.006446  0.000238  0.000085   
3395907  0.023062  0.000834  0.929167  0.005722  0.003390  0.000293  0.000103   
3395944  0.024862  0.000596  0.932002  0.009484  0.011220  0.000253  0.000874   
3395987  0.011131  0.000363  0.980682  0.004085  0.002434  0.000157  0.000104   
3396002  0.011236  0.000359  0.980878  0.003948  0.002296  0.000158  0.000056   
3396045  0.013416  0.001658  0.976683  0.003093  0.000403  0.000304  0.000116   
3396085  0.010390  0.000540  0.953430  0.007012  0.007519  0.000221  0.000451   
3396086  0.008967  0.000364  0.981011  0.004602  0.003534  0.000156  0.000308   
3396088  0.020356  0.028772  0.907025  0.002960  0.002257  0.000279  0.000113   
3396117  0.015046  0.001720  0.929686  0.007192

In [232]:
find = test[test['max_proba']>=0.9]
find['max_proba_to_pred'].value_counts()

KeyError: 'max_proba'

In [234]:
submit = pd.DataFrame()
submit['sid'] = test.index
submit['pred'] = test_pred
# submit['click_mode'] = test['click_mode'].values
submit.head(10)

sid  pred
0  2000000     2
1  2000001     1
2  2000002     7
3  2000003     2
4  2000004     3
5  2000005     1
6  2000006     5
7  2000007     2
8  2000008     1
9  2000009     3

In [236]:
# f1_score(submit['click_mode'],submit['pred'],average='weighted')

In [237]:
submit[['sid','pred']].to_csv("../submit/6862lgb_post.csv",index=False,header=False)

In [106]:
a1 =[0.92348139, 0.71086394, 0.65876489, 1.55548237, 1.73545927, 0.62715862,
 1.45702358, 0.59522381, 1.18419033, 0.57798275, 0.90171286, 1.05940425,]

In [109]:
a3 = [1.17, 0.89, 0.65, 1.97, 2.78, 0.75, 1.67, 0.82, 1.35, 0.7, 1.02, 1.0]

In [107]:
a2=[1.36738918, 1.03790291, 0.77733245, 2.33533351, 3.25118434, 0.82638933,
 1.9516095,  0.95423545, 1.52848168, 0.88731548, 1.19048762, 1.12236339,]

In [115]:
a4=[1.2717398,  0.97906011, 0.7051182,  2.13323559, 2.09161593, 0.99742707,
 2.09484136, 0.84893617, 1.97479275, 0.77382245, 1.04814823, 1.01177361,]

In [108]:
np.corrcoef(a1,a2)

array([[1.        , 0.93978317],
       [0.93978317, 1.        ]])

In [110]:
np.corrcoef(a1,a3)

array([[1.        , 0.94494207],
       [0.94494207, 1.        ]])

In [111]:
np.corrcoef(a2,a3)

array([[1.        , 0.99890716],
       [0.99890716, 1.        ]])

In [116]:
np.corrcoef(a1,a4)

array([[1.        , 0.93074962],
       [0.93074962, 1.        ]])

In [117]:
np.corrcoef(a2,a4)

array([[1.        , 0.86581154],
       [0.86581154, 1.        ]])

In [118]:
np.corrcoef(a3,a4)

array([[1.        , 0.87289529],
       [0.87289529, 1.        ]])

In [122]:
j1 = optR.predict(cv_pred, a1)
j2 = optR.predict(cv_pred, a2)
j3 = optR.predict(cv_pred, a3)
j4 = optR.predict(cv_pred, a4)


In [125]:
np.corrcoef(np.argmax(j1.values,axis=1),np.argmax(j2.values,axis=1))

array([[1.        , 0.97284843],
       [0.97284843, 1.        ]])

In [127]:
np.corrcoef(np.argmax(j1.values,axis=1),np.argmax(j4.values,axis=1))

array([[1.        , 0.97295046],
       [0.97295046, 1.        ]])

In [128]:
np.corrcoef(np.argmax(j2.values,axis=1),np.argmax(j4.values,axis=1))

array([[1.        , 0.97884222],
       [0.97884222, 1.        ]])

In [133]:
submit = []
jj1 = np.argmax(j1.values,axis=1)
jj2 = np.argmax(j2.values,axis=1)
jj4 = np.argmax(j4.values,axis=1)

for i in tqdm(range(len(jj2))):
    if jj1[i]==jj2[i]:
        submit.append(jj1[i])
    elif jj1[i]==jj4[i]:
        submit.append(jj1[i])
    elif jj2[i]==jj4[i]:
        submit.append(jj2[i])
    else:
        submit.append(jj2[i])


100%|██████████| 2000000/2000000 [00:01<00:00, 1341329.35it/s]

In [134]:
f1_score(y,submit,average='weighted')

0.6788562137172918